### ISSUE TITLE
[Bug]: swww install path is not quite right

### ISSUE THREAD

**Issue by PIPIPIG233666** [beatussum/hyprland-overlay#1]
### What happened?

https://github.com/beatussum/hyprland-overlay/blob/2b3e7bf7ac3c8eaa2a020297387e273b2ea8a4eb/gui-apps/swww/swww-0.9.5.ebuild#L289
should be more universal

somehow my gentoo install has rustc as follows:
```
❯ rustc -Vv
rustc 1.80.1 (3f5fd8dd4 2024-08-06) (gentoo)
binary: rustc
commit-hash: 3f5fd8dd41153bc5fdca9427e9e05be2c767ba23
commit-date: 2024-08-06
host: x86_64-unknown-linux-gnu
release: 1.80.1
LLVM version: 18.1.8
```

since host is `x86_64-unknown-linux-gnu`, the target is `target/x86_64-unknown-linux-gnu/release` instead of `target/release`

### Terms

- [X] I agree to follow [this project's code of conduct](https://github.com/beatussum/hyprland-overlay/blob/main/CODE_OF_CONDUCT.md).
- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).

**Comment by beatussum** [comment]
It should be fixed
